package de.fhdw.ergoholics.brainphaser.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CHALLENGE".
 */
public class Challenge {

    private Long id;
    private int challengeType;
    /** Not-null value. */
    private String question;
    private long categoryId;

    public Challenge() {
    }

    public Challenge(Long id) {
        this.id = id;
    }

    public Challenge(Long id, int challengeType, String question, long categoryId) {
        this.id = id;
        this.challengeType = challengeType;
        this.question = question;
        this.categoryId = categoryId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getChallengeType() {
        return challengeType;
    }

    public void setChallengeType(int challengeType) {
        this.challengeType = challengeType;
    }

    /** Not-null value. */
    public String getQuestion() {
        return question;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setQuestion(String question) {
        this.question = question;
    }

    public long getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(long categoryId) {
        this.categoryId = categoryId;
    }

}
