package de.fhdw.ergoholics.brainphaser.model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import de.fhdw.ergoholics.brainphaser.model.Completion;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COMPLETION".
*/
public class CompletionDao extends AbstractDao<Completion, Long> {

    public static final String TABLENAME = "COMPLETION";

    /**
     * Properties of entity Completion.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Stage = new Property(1, Integer.class, "stage", false, "STAGE");
        public final static Property LastCompleted = new Property(2, java.util.Date.class, "lastCompleted", false, "LAST_COMPLETED");
        public final static Property UserId = new Property(3, long.class, "userId", false, "USER_ID");
        public final static Property ChallengeId = new Property(4, long.class, "challengeId", false, "CHALLENGE_ID");
    };

    private DaoSession daoSession;

    private Query<Completion> user_CompletionsQuery;

    public CompletionDao(DaoConfig config) {
        super(config);
    }
    
    public CompletionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COMPLETION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"STAGE\" INTEGER," + // 1: stage
                "\"LAST_COMPLETED\" INTEGER," + // 2: lastCompleted
                "\"USER_ID\" INTEGER NOT NULL ," + // 3: userId
                "\"CHALLENGE_ID\" INTEGER NOT NULL );"); // 4: challengeId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COMPLETION\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Completion entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer stage = entity.getStage();
        if (stage != null) {
            stmt.bindLong(2, stage);
        }
 
        java.util.Date lastCompleted = entity.getLastCompleted();
        if (lastCompleted != null) {
            stmt.bindLong(3, lastCompleted.getTime());
        }
        stmt.bindLong(4, entity.getUserId());
        stmt.bindLong(5, entity.getChallengeId());
    }

    @Override
    protected void attachEntity(Completion entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Completion readEntity(Cursor cursor, int offset) {
        Completion entity = new Completion( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // stage
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // lastCompleted
            cursor.getLong(offset + 3), // userId
            cursor.getLong(offset + 4) // challengeId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Completion entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setStage(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setLastCompleted(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setUserId(cursor.getLong(offset + 3));
        entity.setChallengeId(cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Completion entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Completion entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "completions" to-many relationship of User. */
    public List<Completion> _queryUser_Completions(long userId) {
        synchronized (this) {
            if (user_CompletionsQuery == null) {
                QueryBuilder<Completion> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.UserId.eq(null));
                user_CompletionsQuery = queryBuilder.build();
            }
        }
        Query<Completion> query = user_CompletionsQuery.forCurrentThread();
        query.setParameter(0, userId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getChallengeDao().getAllColumns());
            builder.append(" FROM COMPLETION T");
            builder.append(" LEFT JOIN CHALLENGE T0 ON T.\"CHALLENGE_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Completion loadCurrentDeep(Cursor cursor, boolean lock) {
        Completion entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Challenge challenge = loadCurrentOther(daoSession.getChallengeDao(), cursor, offset);
         if(challenge != null) {
            entity.setChallenge(challenge);
        }

        return entity;    
    }

    public Completion loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Completion> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Completion> list = new ArrayList<Completion>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Completion> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Completion> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
