package de.fhdw.ergoholics.brainphaser.model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import de.fhdw.ergoholics.brainphaser.model.Settings;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SETTINGS".
*/
public class SettingsDao extends AbstractDao<Settings, Long> {

    public static final String TABLENAME = "SETTINGS";

    /**
     * Properties of entity Settings.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TimeBoxStage1 = new Property(1, java.util.Date.class, "timeBoxStage1", false, "TIME_BOX_STAGE1");
        public final static Property TimeBoxStage2 = new Property(2, java.util.Date.class, "timeBoxStage2", false, "TIME_BOX_STAGE2");
        public final static Property TimeBoxStage3 = new Property(3, java.util.Date.class, "timeBoxStage3", false, "TIME_BOX_STAGE3");
        public final static Property TimeBoxStage4 = new Property(4, java.util.Date.class, "timeBoxStage4", false, "TIME_BOX_STAGE4");
        public final static Property TimeBoxStage5 = new Property(5, java.util.Date.class, "timeBoxStage5", false, "TIME_BOX_STAGE5");
        public final static Property TimeBoxStage6 = new Property(6, java.util.Date.class, "timeBoxStage6", false, "TIME_BOX_STAGE6");
        public final static Property UserId = new Property(7, long.class, "userId", false, "USER_ID");
    };

    private DaoSession daoSession;


    public SettingsDao(DaoConfig config) {
        super(config);
    }
    
    public SettingsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SETTINGS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"TIME_BOX_STAGE1\" INTEGER," + // 1: timeBoxStage1
                "\"TIME_BOX_STAGE2\" INTEGER," + // 2: timeBoxStage2
                "\"TIME_BOX_STAGE3\" INTEGER," + // 3: timeBoxStage3
                "\"TIME_BOX_STAGE4\" INTEGER," + // 4: timeBoxStage4
                "\"TIME_BOX_STAGE5\" INTEGER," + // 5: timeBoxStage5
                "\"TIME_BOX_STAGE6\" INTEGER," + // 6: timeBoxStage6
                "\"USER_ID\" INTEGER NOT NULL );"); // 7: userId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SETTINGS\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Settings entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        java.util.Date timeBoxStage1 = entity.getTimeBoxStage1();
        if (timeBoxStage1 != null) {
            stmt.bindLong(2, timeBoxStage1.getTime());
        }
 
        java.util.Date timeBoxStage2 = entity.getTimeBoxStage2();
        if (timeBoxStage2 != null) {
            stmt.bindLong(3, timeBoxStage2.getTime());
        }
 
        java.util.Date timeBoxStage3 = entity.getTimeBoxStage3();
        if (timeBoxStage3 != null) {
            stmt.bindLong(4, timeBoxStage3.getTime());
        }
 
        java.util.Date timeBoxStage4 = entity.getTimeBoxStage4();
        if (timeBoxStage4 != null) {
            stmt.bindLong(5, timeBoxStage4.getTime());
        }
 
        java.util.Date timeBoxStage5 = entity.getTimeBoxStage5();
        if (timeBoxStage5 != null) {
            stmt.bindLong(6, timeBoxStage5.getTime());
        }
 
        java.util.Date timeBoxStage6 = entity.getTimeBoxStage6();
        if (timeBoxStage6 != null) {
            stmt.bindLong(7, timeBoxStage6.getTime());
        }
        stmt.bindLong(8, entity.getUserId());
    }

    @Override
    protected void attachEntity(Settings entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Settings readEntity(Cursor cursor, int offset) {
        Settings entity = new Settings( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)), // timeBoxStage1
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // timeBoxStage2
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)), // timeBoxStage3
            cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)), // timeBoxStage4
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)), // timeBoxStage5
            cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)), // timeBoxStage6
            cursor.getLong(offset + 7) // userId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Settings entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTimeBoxStage1(cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)));
        entity.setTimeBoxStage2(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setTimeBoxStage3(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
        entity.setTimeBoxStage4(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
        entity.setTimeBoxStage5(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
        entity.setTimeBoxStage6(cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)));
        entity.setUserId(cursor.getLong(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Settings entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Settings entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUserDao().getAllColumns());
            builder.append(" FROM SETTINGS T");
            builder.append(" LEFT JOIN USER T0 ON T.\"USER_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Settings loadCurrentDeep(Cursor cursor, boolean lock) {
        Settings entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        User settings = loadCurrentOther(daoSession.getUserDao(), cursor, offset);
         if(settings != null) {
            entity.setSettings(settings);
        }

        return entity;    
    }

    public Settings loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Settings> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Settings> list = new ArrayList<Settings>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Settings> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Settings> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
