package de.fhdw.ergoholics.brainphaser.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SETTINGS".
 */
public class Settings {

    private Long id;
    private java.util.Date timeBoxStage1;
    private java.util.Date timeBoxStage2;
    private java.util.Date timeBoxStage3;
    private java.util.Date timeBoxStage4;
    private java.util.Date timeBoxStage5;
    private java.util.Date timeBoxStage6;

    public Settings() {
    }

    public Settings(Long id) {
        this.id = id;
    }

    public Settings(Long id, java.util.Date timeBoxStage1, java.util.Date timeBoxStage2, java.util.Date timeBoxStage3, java.util.Date timeBoxStage4, java.util.Date timeBoxStage5, java.util.Date timeBoxStage6) {
        this.id = id;
        this.timeBoxStage1 = timeBoxStage1;
        this.timeBoxStage2 = timeBoxStage2;
        this.timeBoxStage3 = timeBoxStage3;
        this.timeBoxStage4 = timeBoxStage4;
        this.timeBoxStage5 = timeBoxStage5;
        this.timeBoxStage6 = timeBoxStage6;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getTimeBoxStage1() {
        return timeBoxStage1;
    }

    public void setTimeBoxStage1(java.util.Date timeBoxStage1) {
        this.timeBoxStage1 = timeBoxStage1;
    }

    public java.util.Date getTimeBoxStage2() {
        return timeBoxStage2;
    }

    public void setTimeBoxStage2(java.util.Date timeBoxStage2) {
        this.timeBoxStage2 = timeBoxStage2;
    }

    public java.util.Date getTimeBoxStage3() {
        return timeBoxStage3;
    }

    public void setTimeBoxStage3(java.util.Date timeBoxStage3) {
        this.timeBoxStage3 = timeBoxStage3;
    }

    public java.util.Date getTimeBoxStage4() {
        return timeBoxStage4;
    }

    public void setTimeBoxStage4(java.util.Date timeBoxStage4) {
        this.timeBoxStage4 = timeBoxStage4;
    }

    public java.util.Date getTimeBoxStage5() {
        return timeBoxStage5;
    }

    public void setTimeBoxStage5(java.util.Date timeBoxStage5) {
        this.timeBoxStage5 = timeBoxStage5;
    }

    public java.util.Date getTimeBoxStage6() {
        return timeBoxStage6;
    }

    public void setTimeBoxStage6(java.util.Date timeBoxStage6) {
        this.timeBoxStage6 = timeBoxStage6;
    }

}
