package de.fhdw.ergoholics.brainphaser.model;

import de.fhdw.ergoholics.brainphaser.model.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STATISTICS".
 */
public class Statistics {

    private Long id;
    private Boolean succeeded;
    private java.util.Date time;
    private long userId;
    private long challengeId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient StatisticsDao myDao;

    private Challenge statistic;
    private Long statistic__resolvedKey;


    public Statistics() {
    }

    public Statistics(Long id) {
        this.id = id;
    }

    public Statistics(Long id, Boolean succeeded, java.util.Date time, long userId, long challengeId) {
        this.id = id;
        this.succeeded = succeeded;
        this.time = time;
        this.userId = userId;
        this.challengeId = challengeId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getStatisticsDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getSucceeded() {
        return succeeded;
    }

    public void setSucceeded(Boolean succeeded) {
        this.succeeded = succeeded;
    }

    public java.util.Date getTime() {
        return time;
    }

    public void setTime(java.util.Date time) {
        this.time = time;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public long getChallengeId() {
        return challengeId;
    }

    public void setChallengeId(long challengeId) {
        this.challengeId = challengeId;
    }

    /** To-one relationship, resolved on first access. */
    public Challenge getStatistic() {
        long __key = this.challengeId;
        if (statistic__resolvedKey == null || !statistic__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ChallengeDao targetDao = daoSession.getChallengeDao();
            Challenge statisticNew = targetDao.load(__key);
            synchronized (this) {
                statistic = statisticNew;
            	statistic__resolvedKey = __key;
            }
        }
        return statistic;
    }

    public void setStatistic(Challenge statistic) {
        if (statistic == null) {
            throw new DaoException("To-one property 'challengeId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.statistic = statistic;
            challengeId = statistic.getId();
            statistic__resolvedKey = challengeId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
